Реализация практики в рамках проекта №1
Krayseer/splash-mobile pull request #1
Opened 2024-10-21 18:32 UTC by Krayseer

2024-10-21 18:41 UTC, Krayseer commented
Занимаюсь партнерским приложением

2024-10-24 07:32 UTC, dekabrsky commented on partner-app/src/main/java/ru/anykeyers/partner_app/adapter/OrderAdapter.kt
> +        var id: TextView = itemView.findViewById(R.id.order_id)
Используй viewBinding

2024-10-24 07:33 UTC, dekabrsky commented on partner-app/src/main/java/ru/anykeyers/partner_app/adapter/ServiceAndBoxPagerAdapter.kt
> +            0 -> ServiceFragment()
Заведи список фрагментов и бери по индексу

2024-10-24 07:35 UTC, dekabrsky commented on partner-app/src/main/java/ru/anykeyers/partner_app/fragment/BoxFragment.kt
> +        boxAdapter = BoxAdapter(boxService.loadBoxes(1))
Используй MVVM - вынеси такие операции во вьюмодель

2024-10-24 07:39 UTC, dekabrsky requested changes
Прошу обратить внимание на viewBinding, MVVM/MVP, стили - это очень облегчит жизнь

2024-10-24 07:39 UTC, dekabrsky commented on partner-app/src/main/java/ru/anykeyers/partner_app/fragment/BoxFragment.kt
> +    private lateinit var boxAdapter: BoxAdapter
Можно использовать by lazy

2024-10-24 07:39 UTC, dekabrsky commented on partner-app/src/main/java/ru/anykeyers/partner_app/fragment/ServiceAndBoxFragment.kt
> +    private lateinit var tabLayout: TabLayout
А зачем они как свойства?

2024-10-24 07:39 UTC, dekabrsky commented on partner-app/src/main/res/layout/item_service.xml
> +                android:textSize="16sp"
Сложно управлять множеством текстовых полей, которые фактически одного стиля, но он каждый раз описывается заново. Создай стили или используй готовые

2024-10-26 06:39 UTC, merged

2024-10-27 18:56 UTC, Krayseer commented
Все замечания были поправлены в пулл реквесте следующей практики